export const userRoutes = [
    "/",
    "/login",
    "/auth/callback",
    "/logout",
    "/signup",
    "/email/verification",
    "/confirm/password",
    "/confirm/password/reset",
    "/user/profile",
    "/user/profile/category",
    "/user/profile/nickname",
    "/user/profile/layout",
    "/community/questions",
    "/community/general",
    "/community/team-recruit",
    "/teams/:teamId/main",
    "/teams/:teamId/manage/users",
    "/teams/:teamId/manage/settings",
    "/teams/:teamId/study",
    "/teams/:teamId/study/:studyId",
    "/teams/:teamId/book/search",
    "/teams/:teamId/book/search/:bookId",
    "/teams/:teamId/questions",
    "/teams/:teamId/questions/:postId",
    "/teams/:teamId/questions/:postId/edit",
  ];
  