org: persii
app: esquad-monorepo
service: service-notification
frameworkVersion: '^3.15.0'

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:AWS_REGION}
  environment:
    STORAGE_DYNAMODB_TABLE: ${env:METADATA_TABLE}
    TEAM_DYNAMODB_TABLE: ${env:TEAM_TABLE}
    NOTIFICATION_DYNAMODB_TABLE: ${env:NOTIFICATION_TABLE}
    SNS_TOPIC_PREFIX: StudyPageFileTopic
    AWS_ACCOUNT_ID: ${env:AWS_ACCOUNT_ID}
    METADATA_TABLE_STREAM_LABEL: ${env:METADATA_TABLE_STREAM_LABEL}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:DescribeStream
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:ListStreams
        - sns:Publish
      Resource:
        - arn:aws:dynamodb:${env:AWS_REGION}:${env:AWS_ACCOUNT_ID}:table/${env:TEAM_TABLE}
        - arn:aws:dynamodb:${env:AWS_REGION}:${env:AWS_ACCOUNT_ID}:table/${env:METADATA_TABLE}
        - arn:aws:dynamodb:${env:AWS_REGION}:${env:AWS_ACCOUNT_ID}:table/${env:NOTIFICATION_TABLE}
        - arn:aws:sns:${env:AWS_REGION}:${env:AWS_ACCOUNT_ID}:StudyPageFileTopic

functions:
  notifyUsersOnFileUpload:
    handler: ./service/notifyUsersOnFileUpload.handler # Lambda 핸들러 함수
    environment:
      TEAM_TABLE_NAME: ${env:TEAM_TABLE}
      NOTIFICATIONS_TABLE_NAME: ${env:NOTIFICATION_TABLE}
      FILE_CHANGE_NOTIFICATION_TOPIC:
        Ref: StudyPageNotificationsTopic
    events:
      - stream:
          type: dynamodb # DynamoDB Streams 트리거
          arn: arn:aws:dynamodb:${env:AWS_REGION}:${env:AWS_ACCOUNT_ID}:table/${env:METADATA_TABLE}/stream/${env:METADATA_TABLE_STREAM_LABEL}
          batchSize: 5              # 스트림 배치 처리 크기
          startingPosition: LATEST  # 최신 이벤트부터 시작

resources:
  Resources:
    # DynamoDB 테이블 정의
    NotificationsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:NOTIFICATION_TABLE}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    StudyPageNotificationsTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: StudyPageFileTopic   # SNS Topic 명

    HTTPSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn:
          Ref: StudyPageNotificationsTopic
        Protocol: http
        Endpoint: http://localhost:5173/notifications

  Outputs:
    NotificationsTableName:
      Description: ARN of the Notifications Table
      Value: ${env:NOTIFICATION_TABLE}
    SNSTopicARN:
      Description: ARN of the SNS Topic
      Value:
        Ref: StudyPageNotificationsTopic # 기존 `StudyPageFileSNSTopic`에서 수정
      Export:
        Name: StudyPageNotificationsTopic

useDotenv: true